### PR TITLE
Add support for options flow

### PR DESCRIPTION
**Pull request by postlund**
With this PR, all the settings available in YAML can also be configured via options flow (e.g. entity prefix and filters). The integration is automatically reloaded after changing something, so changes are instantly reflected.

I'm not sure I'm finished yet, I need to have another look at the code. But it would be great to get some test run with this. So please try it out. Just add an integration via Configuration -> Integrations and press `Options`.

### CODE REVIEW

**Comment by postlund** [comment]
I have implemented support for discovery as well, seems to work. It build upon this PR so it must be merged first though.

**Comment by lukas-hetzenecker** [comment]
Wow, again really impressive! :partying_face: 

Just a nitpick about the pop-up options dialog, which I think is a bit confusing:

- In the first dialog, it feels like one has to enter a "Entity prefix" - although this is entirely optional (and I'd even suggest to not use one). 
- With the "Submit" button, it looks like this are all available options. It's a bit counterintuitive that another popup dialog opens
- I think it would be great to see all possible options in a single page

As a suggestion I'd propose a configuration page (instead of a dialog), as e.g. MQTT or ozw have. The now separate options dialogs could then be in a single page with different cards. What do you think about that?

And have I already said I love the auto-populated "Domain and entity filters" fields? :smile:

**Comment by postlund** [comment]
Right 😉

Yeah, wording and descriptions can certainly be improved. The "look-and-feel" however is not something I can do much about. Having only a `Submit` button is part of the data entry flow framework used for config/option flows and cannot to my knowledge be changed. The main reason for splitting up into multiple pages are 1) to not clutter too much as settings can't be grouped 2) simplify implementation. Especially 2), since the code would become a complete unmaintainable mess if everything was presented in the same step. Especially my work-around for adding items to a list.

Don't think it's possible to add custom configuration pages for custom components? They seem to be bundled with the frontend:

https://github.com/home-assistant/frontend/tree/8275ac5853ccbc94a343672998e36a04436184f6/src/panels/config/integrations/integration-panels

So even if that would be pretty cool, I don't think it's technically possible.

Yeah, auto-populating stuff is awesome 😀 Did a similar concept for datapoints in the `localtuya` custom component. So couldn't resist to do it here as well 😉

**Comment by lukas-hetzenecker** [comment]
> Don't think it's possible to add custom configuration pages for custom components?

Ah damn. Yeah, now that you mention it I think there was even some recent discussion about that.
And should have definitely remembered it's hardcoded in the frontend, as I regularly check that repo for more customizability of the ozw component. 🤦‍♂️😂

But you're totally right, then we're really out of options - maybe some "Step x/y" in the header or something similar could help to tell the user that there's more to come?

**Comment by postlund** [comment]
> And should have definitely remembered it's hardcoded in the frontend, as I regularly check that repo for more customizability of the ozw component. 🤦‍♂️😂

😂

> But you're totally right, then we're really out of options - maybe some "Step x/y" in the header or something similar could help to tell the user that there's more to come?

That's doable, can just hardcode it into the title. I'll fix it now and push an update.

**Comment by postlund** [comment]
I added step number to titles and made it more clear that entity prefix is optional.

**Comment by lukas-hetzenecker** [comment]
Perfect, thanks

**Comment by lukas-hetzenecker** [comment]
Merged - can't wait to see how you've managed to implement discovery :)

**Comment by danmed** [comment]
I'm a bit confused.. i've got this installed via HACS.. and i've entered the YAML to get it working (All good).. but i can't see anything in configuration > integrations that i can add to see an options link.. am i looking at this wrong?

**Comment by postlund** [comment]
There's no release out with these changes yet. I have not finished the import of YAML config into a config entry either, so stuff configured via YAML vs config flow live in separate worlds. Once I do you will see it under Integrations. You will however not be able to use options flow with YAML, you will have to set up via Integrations for that.

**Pull request merged**
