### PR TITLE
Add discovery support

### PR DESCRIPTION
**Pull request by postlund**
@lukas-hetzenecker Here you have the discovery support 🕺

### CODE REVIEW

**Comment by lukas-hetzenecker** [comment]
Perfect, works great! :man_dancing:

**Comment by lukas-hetzenecker** [comment]
Is even more coming, or do you want me to publish a new release now? ;)

**Comment by postlund** [comment]
The final piece is to implement import of YAML config into a config entry and adding a reload service, so the YAML config can be reloaded without having to restart. Should be fairly straight forward to implement.

**Comment by postlund** [comment]
An oh, @lukas-hetzenecker, you should break out your artistic skills and submit a fabulous icon to the `brands` repo. It will make things look better.

**Comment by lukas-hetzenecker** [comment]
remote_homeassistant

@postlund that's all I can do, what do you think? :-)

**Comment by postlund** [comment]
@lukas-hetzenecker Fantastic! 😎

**Comment by lukas-hetzenecker** [comment]
home-assistant/brands#2024 :raised_hands:

**Comment by postlund** [comment]
@lukas-hetzenecker The new logo looks swell 👍

I'm working on the YAML import now, it's basically done. There's one issue however: `api_password`. As I didn't implement support for it in the config flow, there's no "easy" way to to support it. Ok, maybe it's not *that* hard to implement, but since it's deprecated and less secure than `access_token`, may I suggest that we deprecate it now so I don't have to spend time adding support for it? It's a quick change to do for me.

**Pull request merged**
